# Generated by Django 3.0.6 on 2020-06-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('auther', models.CharField(max_length=20, verbose_name='Author')),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
