# Generated by Django 3.0.6 on 2020-05-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('email', models.CharField(max_length=100, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
